#!/bin/sh
# We assume that we are the top level of this project
rm -f target/*.class
javac -cp /Users/sri/.m2/repository/junit/junit/4.10/junit-4.10.jar -d target src/*.java
cd target 1 > /dev/null
java kata02.Chopper
cd ..
